// FETCH USER CONSTANTS
export const FETCH_USER = "FETCH_USER";
export const FETCH_USER_LOADING = "FETCH_USER_LOADING";
export const FETCH_USER_ERROR = "FETCH_USER_ERROR";

// Update User
export const UPDATING_USER = "UPDATING_USER";
export const UPDATED_USER = "UPDATED_USER";
export const UPDATING_USER_ERROR = "FETCH_USER_ERROR";

// FETCH WALLET CONSTANTS
export const FETCH_WALLET = "FETCH_WALLET";
export const FETCH_WALLET_LOADING = "FETCH_WALLET_LOADING";
export const FETCH_WALLET_ERROR = "FETCH_WALLET_ERROR";
export const WALLET_TRANSACTIONS = "WALLET_TRANSACTIONS";

// WITHDRAW TRANSACTION
export const CREATE_WITHDRAW_LOADING = "CREATE_WITHDRAW_LOADING";
export const CREATE_WITHDRAW_ERROR = "CREATE_WITHDRAW_ERROR";
export const WITHDRAW_SUCCESS = "WITHDRAW_SUCCESS";

//PURCHASE FLOW
export const PURCHASE_FLOW_STEP = "PURCHASE_FLOW_STEP";

//PURCHASE DATA
export const PURCHASE_FLOW_DATA = "PURCHASE_FLOW_DATA";

// Cryptonator Data
export const CRYPTONATOR = "CRYPTONATOR";

// Transaction
export const TRANSACTION_IN_PROGRESS = "TRANSACTION_IN_PROGRESS";
export const TRANSACTION_SUCCESSFUL = "TRANSACTION_SUCCESSFUL";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";

// Login/Signup
export const AUTH_EMAIL_ERROR = "AUTH_EMAIL_ERROR";
export const AUTH_PASSWORD_ERROR = "AUTH_PASSWORD_ERROR";
export const EMAIL_VERIFIED = "EMAIL_VERIFIED";

// Account
export const PASSWORD_CHANGED = "PASSWORD_CHANGED";
export const EMAIL_CONFIRMED = "EMAIL_CONFIRMED";
export const LOADING = "LOADING";
export const ERROR = "ERROR";

//Navigation
export const NAV_DRAWER_TOGGLE = "NAV_DRAWER_TOGGLE";


//Send Forgot Password Email
export const FORGOT_PASSWORD_EMAIL_SENT = "FORGOT_PASSWORD_EMAIL_SENT";

// LOGIN Flow
export const LOGIN_STATE = "LOGIN_STATE";

